<?php

namespace App\Http\Middleware;

use App\CodeResponse;
use App\Exceptions\BaseException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }

    protected function unauthenticated($request, array $guards)
    {
        if ($request->expectsJson() || in_array('wx', $guards)) {
            throw new BaseException(CodeResponse::UNLOGIN);
        }
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }
}
